// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP5nZrPwe39Pm7a-p_D2UsuPPydF9f6gI',
    appId: '1:40507665346:web:fc439b4a427720432ac45b',
    messagingSenderId: '40507665346',
    projectId: 'recipeapp-a1023',
    authDomain: 'recipeapp-a1023.firebaseapp.com',
    storageBucket: 'recipeapp-a1023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKdDY6u6tiqjaaIA9h5zaQw7olHGEWKk',
    appId: '1:40507665346:android:f0d24a721d0c907d2ac45b',
    messagingSenderId: '40507665346',
    projectId: 'recipeapp-a1023',
    storageBucket: 'recipeapp-a1023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABo3e4B4mR0vYQrRvgQafi_i0BSFhkyyo',
    appId: '1:40507665346:ios:a10db8f356818bae2ac45b',
    messagingSenderId: '40507665346',
    projectId: 'recipeapp-a1023',
    storageBucket: 'recipeapp-a1023.appspot.com',
    iosClientId: '40507665346-1pu1vth0ci1rl7ckm6pe0sb9iu3qtc41.apps.googleusercontent.com',
    iosBundleId: 'com.example.yummyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABo3e4B4mR0vYQrRvgQafi_i0BSFhkyyo',
    appId: '1:40507665346:ios:2e16a498a147da662ac45b',
    messagingSenderId: '40507665346',
    projectId: 'recipeapp-a1023',
    storageBucket: 'recipeapp-a1023.appspot.com',
    iosClientId: '40507665346-aj8bihirf2kc5b0ksmd8a121a1g34etg.apps.googleusercontent.com',
    iosBundleId: 'com.example.yummyApp.RunnerTests',
  );
}
